// Currency data mapping currencies to countries.
// Each entry: { code, name, symbol, countries: [ISO3166-1 numeric ids used by world-atlas map] }
// If a currency is used by multiple countries, all ids are listed and any is accepted.
const CURRENCIES = [
  { code: "AED",  name: "UAE Dirham",            symbol: "د.إ",                     countries: [784] },
  { code: "AFN",  name: "Afghani",               symbol: "؋",                       countries: [4] },
  { code: "ALL",  name: "Albanian Lek",          symbol: "L",                        countries: [8] },
  { code: "AMD",  name: "Armenian Dram",         symbol: "֏",                        countries: [51] },
  { code: "AOA",  name: "Kwanza",                symbol: "Kz",                       countries: [24] },
  { code: "ARS",  name: "Argentine Peso",        symbol: "$",                        countries: [32] },
  { code: "AUD",  name: "Australian Dollar",     symbol: "A$",                       countries: [36, 296, 520] },
  { code: "AZN",  name: "Azerbaijan Manat",      symbol: "₼",                        countries: [31] },
  { code: "BAM",  name: "Convertible Mark",      symbol: "KM",                       countries: [70] },
  { code: "BBD",  name: "Barbados Dollar",       symbol: "Bds$",                     countries: [52] },
  { code: "BDT",  name: "Taka",                  symbol: "৳",                        countries: [50] },
  { code: "BGN",  name: "Bulgarian Lev",         symbol: "лв",                       countries: [100] },
  { code: "BHD",  name: "Bahraini Dinar",        symbol: "د.ب",                      countries: [48] },
  { code: "BIF",  name: "Burundi Franc",         symbol: "FBu",                      countries: [108] },
  { code: "BND",  name: "Brunei Dollar",         symbol: "B$",                       countries: [96] },
  { code: "BOB",  name: "Boliviano",             symbol: "Bs",                       countries: [68] },
  { code: "BRL",  name: "Brazilian Real",        symbol: "R$",                       countries: [76] },
  { code: "BSD",  name: "Bahamian Dollar",       symbol: "B$",                       countries: [44] },
  { code: "BTN",  name: "Ngultrum",              symbol: "Nu",                       countries: [64] },
  { code: "BWP",  name: "Pula",                  symbol: "P",                        countries: [72] },
  { code: "BYN",  name: "Belarusian Ruble",      symbol: "Br",                       countries: [112] },
  { code: "BZD",  name: "Belize Dollar",         symbol: "BZ$",                      countries: [84] },
  { code: "CAD",  name: "Canadian Dollar",       symbol: "C$",                       countries: [124] },
  { code: "CDF",  name: "Congolese Franc",       symbol: "FC",                       countries: [180] },
  { code: "CHF",  name: "Swiss Franc",           symbol: "Fr",                       countries: [756, 438] },
  { code: "CLP",  name: "Chilean Peso",          symbol: "$",                        countries: [152] },
  { code: "CNY",  name: "Chinese Yuan (Renminbi)", symbol: "¥",                      countries: [156] },
  { code: "COP",  name: "Colombian Peso",        symbol: "$",                        countries: [170] },
  { code: "CRC",  name: "Costa Rican Colon",     symbol: "₡",                        countries: [188] },
  { code: "CUP",  name: "Cuban Peso",            symbol: "$",                        countries: [192] },
  { code: "CVE",  name: "Cabo Verde Escudo",     symbol: "Esc",                      countries: [132] },
  { code: "CZK",  name: "Czech Koruna",          symbol: "Kč",                       countries: [203] },
  { code: "DJF",  name: "Djibouti Franc",        symbol: "Fdj",                      countries: [262] },
  { code: "DKK",  name: "Danish Krone",          symbol: "kr",                       countries: [208, 234, 304] },
  { code: "DOP",  name: "Dominican Peso",        symbol: "RD$",                      countries: [214] },
  { code: "DZD",  name: "Algerian Dinar",        symbol: "دج",                       countries: [12] },
  { code: "EGP",  name: "Egyptian Pound",        symbol: "£",                        countries: [818] },
  { code: "ERN",  name: "Nakfa",                 symbol: "Nfk",                      countries: [232] },
  { code: "ETB",  name: "Ethiopian Birr",        symbol: "Br",                       countries: [231] },
  { code: "EUR",  name: "Euro",                  symbol: "€",                        countries: [20, 40, 56, 191, 196, 233, 246, 250, 276, 300, 336, 372, 380, 428, 440, 442, 470, 492, 499, 528, 620, 674, 703, 705, 724] },
  { code: "FJD",  name: "Fiji Dollar",           symbol: "FJ$",                      countries: [242] },
  { code: "GBP",  name: "Pound Sterling",        symbol: "£",                        countries: [826] },
  { code: "GEL",  name: "Lari",                  symbol: "₾",                        countries: [268] },
  { code: "GHS",  name: "Ghana Cedi",            symbol: "GH₵",                      countries: [288] },
  { code: "GMD",  name: "Dalasi",                symbol: "D",                        countries: [270] },
  { code: "GNF",  name: "Guinean Franc",         symbol: "FG",                       countries: [324] },
  { code: "GTQ",  name: "Quetzal",               symbol: "Q",                        countries: [320] },
  { code: "GYD",  name: "Guyana Dollar",         symbol: "G$",                       countries: [328] },
  // Hong Kong is part of China (id 156) on this world map, so China is the click target.
  { code: "HKD",  name: "Hong Kong Dollar",      symbol: "HK$",                      countries: [156] },
  { code: "HNL",  name: "Lempira",               symbol: "L",                        countries: [340] },
  { code: "HTG",  name: "Gourde",                symbol: "G",                        countries: [332] },
  { code: "HUF",  name: "Hungarian Forint",      symbol: "Ft",                       countries: [348] },
  { code: "IDR",  name: "Indonesian Rupiah",     symbol: "Rp",                       countries: [360] },
  { code: "ILS",  name: "Israeli New Shekel",    symbol: "₪",                        countries: [376] },
  { code: "INR",  name: "Indian Rupee",          symbol: "₹",                        countries: [356] },
  { code: "IQD",  name: "Iraqi Dinar",           symbol: "د.ع",                      countries: [368] },
  { code: "IRR",  name: "Iranian Rial",          symbol: "﷼",                        countries: [364] },
  { code: "ISK",  name: "Icelandic Króna",       symbol: "kr",                       countries: [352] },
  { code: "JMD",  name: "Jamaican Dollar",       symbol: "J$",                       countries: [388] },
  { code: "JOD",  name: "Jordanian Dinar",       symbol: "د.أ",                      countries: [400] },
  { code: "JPY",  name: "Japanese Yen",          symbol: "¥",                        countries: [392] },
  { code: "KES",  name: "Kenyan Shilling",       symbol: "KSh",                      countries: [404] },
  { code: "KGS",  name: "Som",                   symbol: "с",                        countries: [417] },
  { code: "KHR",  name: "Riel",                  symbol: "៛",                        countries: [116] },
  { code: "KMF",  name: "Comorian Franc",        symbol: "CF",                       countries: [174] },
  { code: "KRW",  name: "Korean Won",            symbol: "₩",                        countries: [410] },
  { code: "KWD",  name: "Kuwaiti Dinar",         symbol: "د.ك",                      countries: [414] },
  { code: "KZT",  name: "Tenge",                 symbol: "₸",                        countries: [398] },
  { code: "LAK",  name: "Lao Kip",               symbol: "₭",                        countries: [418] },
  { code: "LBP",  name: "Lebanese Pound",        symbol: "ل.ل",                      countries: [422] },
  { code: "LKR",  name: "Sri Lanka Rupee",       symbol: "රු",                       countries: [144] },
  { code: "LRD",  name: "Liberian Dollar",       symbol: "L$",                       countries: [430] },
  { code: "LSL",  name: "Loti",                  symbol: "L",                        countries: [426] },
  { code: "LYD",  name: "Libyan Dinar",          symbol: "ل.د",                      countries: [434] },
  { code: "MAD",  name: "Moroccan Dirham",       symbol: "د.م.",                     countries: [504] },
  { code: "MDL",  name: "Moldovan Leu",          symbol: "L",                        countries: [498] },
  { code: "MGA",  name: "Malagasy Ariary",       symbol: "Ar",                       countries: [450] },
  { code: "MKD",  name: "Denar",                 symbol: "ден",                      countries: [807] },
  { code: "MMK",  name: "Kyat",                  symbol: "K",                        countries: [104] },
  { code: "MNT",  name: "Tugrik",                symbol: "₮",                        countries: [496] },
  { code: "MRU",  name: "Ouguiya",               symbol: "UM",                       countries: [478] },
  { code: "MUR",  name: "Mauritius Rupee",       symbol: "₨",                        countries: [480] },
  { code: "MVR",  name: "Rufiyaa",               symbol: "Rf",                       countries: [462] },
  { code: "MWK",  name: "Malawi Kwacha",         symbol: "MK",                       countries: [454] },
  { code: "MXN",  name: "Mexican Peso",          symbol: "$",                        countries: [484] },
  { code: "MYR",  name: "Malaysian Ringgit",     symbol: "RM",                       countries: [458] },
  { code: "MZN",  name: "Mozambique Metical",    symbol: "MT",                       countries: [508] },
  { code: "NAD",  name: "Namibian Dollar",       symbol: "N$",                       countries: [516] },
  { code: "NGN",  name: "Nigerian Naira",        symbol: "₦",                        countries: [566] },
  { code: "NIO",  name: "Cordoba Oro",           symbol: "C$",                       countries: [558] },
  { code: "NOK",  name: "Norwegian Krone",       symbol: "kr",                       countries: [578] },
  { code: "NPR",  name: "Nepalese Rupee",        symbol: "₨",                        countries: [524] },
  { code: "NZD",  name: "New Zealand Dollar",    symbol: "NZ$",                      countries: [554] },
  { code: "OMR",  name: "Rial Omani",            symbol: "ر.ع.",                     countries: [512] },
  { code: "PAB",  name: "Balboa",                symbol: "B/.",                      countries: [591] },
  { code: "PEN",  name: "Peruvian Sol",          symbol: "S/",                       countries: [604] },
  { code: "PGK",  name: "Kina",                  symbol: "K",                        countries: [598] },
  { code: "PHP",  name: "Philippine Peso",       symbol: "₱",                        countries: [608] },
  { code: "PKR",  name: "Pakistan Rupee",        symbol: "₨",                        countries: [586] },
  { code: "PLN",  name: "Zloty",                 symbol: "zł",                       countries: [616] },
  { code: "PYG",  name: "Guarani",               symbol: "₲",                        countries: [600] },
  { code: "QAR",  name: "Qatari Riyal",          symbol: "ر.ق",                      countries: [634] },
  { code: "RON",  name: "Romanian Leu",          symbol: "lei",                      countries: [642] },
  { code: "RSD",  name: "Serbian Dinar",         symbol: "дин",                      countries: [688] },
  { code: "RUB",  name: "Russian Rouble",        symbol: "₽",                        countries: [643] },
  { code: "RWF",  name: "Rwanda Franc",          symbol: "FRw",                      countries: [646] },
  { code: "SAR",  name: "Saudi Riyal",           symbol: "﷼",                        countries: [682] },
  { code: "SBD",  name: "Solomon Islands Dollar", symbol: "SI$",                     countries: [90] },
  { code: "SCR",  name: "Seychelles Rupee",      symbol: "₨",                        countries: [690] },
  { code: "SDG",  name: "Sudanese Pound",        symbol: "£",                        countries: [729] },
  { code: "SEK",  name: "Swedish Krona",         symbol: "kr",                       countries: [752] },
  { code: "SGD",  name: "Singapore Dollar",      symbol: "S$",                       countries: [702] },
  { code: "SLE",  name: "Leone",                 symbol: "Le",                       countries: [694] },
  { code: "SOS",  name: "Somali Shilling",       symbol: "Sh.So",                    countries: [706] },
  { code: "SRD",  name: "Suriname Dollar",       symbol: "$",                        countries: [740] },
  { code: "SSP",  name: "South Sudanese Pound",  symbol: "£",                        countries: [728] },
  { code: "STN",  name: "Dobra",                 symbol: "Db",                       countries: [678] },
  { code: "SYP",  name: "Syrian Pound",          symbol: "ل.س",                      countries: [760] },
  { code: "SZL",  name: "Lilangeni",             symbol: "L",                        countries: [748] },
  { code: "THB",  name: "Thai Baht",             symbol: "฿",                        countries: [764] },
  { code: "TJS",  name: "Somoni",                symbol: "SM",                       countries: [762] },
  { code: "TMT",  name: "Turkmenistan New Manat", symbol: "m",                       countries: [795] },
  { code: "TND",  name: "Tunisian Dinar",        symbol: "د.ت",                      countries: [788] },
  { code: "TOP",  name: "Pa'anga",               symbol: "T$",                       countries: [776] },
  { code: "TRY",  name: "Turkish Lira",          symbol: "₺",                        countries: [792] },
  { code: "TTD",  name: "Trinidad and Tobago Dollar", symbol: "TT$",                 countries: [780] },
  { code: "TWD",  name: "New Taiwan Dollar",     symbol: "NT$",                      countries: [158] },
  { code: "TZS",  name: "Tanzanian Shilling",    symbol: "TSh",                      countries: [834] },
  { code: "UAH",  name: "Hryvnia",               symbol: "₴",                        countries: [804] },
  { code: "UGX",  name: "Uganda Shilling",       symbol: "USh",                      countries: [800] },
  { code: "USD",  name: "US Dollar",             symbol: "$",                        countries: [218, 222, 583, 584, 585, 626, 630, 840] },
  { code: "UYU",  name: "Peso Uruguayo",         symbol: "$U",                       countries: [858] },
  { code: "UZS",  name: "Uzbekistan Sum",        symbol: "so'm",                     countries: [860] },
  { code: "VES",  name: "Bolívar Soberano",      symbol: "Bs",                       countries: [862] },
  { code: "VND",  name: "Vietnamese Dong",       symbol: "₫",                        countries: [704] },
  { code: "VUV",  name: "Vatu",                  symbol: "VT",                       countries: [548] },
  { code: "WST",  name: "Tala",                  symbol: "WS$",                      countries: [882] },
  { code: "XAF",  name: "CFA Franc (BEAC)",      symbol: "FCFA",                     countries: [120, 140, 148, 178, 226, 266] },
  { code: "XCD",  name: "East Caribbean Dollar", symbol: "EC$",                      countries: [28, 212, 308, 659, 662, 670] },
  { code: "XOF",  name: "CFA Franc (BCEAO)",     symbol: "FCFA",                     countries: [204, 384, 466, 562, 624, 686, 768, 854] },
  { code: "YER",  name: "Yemeni Rial",           symbol: "﷼",                        countries: [887] },
  { code: "ZAR",  name: "South African Rand",    symbol: "R",                        countries: [710] },
  { code: "ZMW",  name: "Zambian Kwacha",        symbol: "K",                        countries: [894] },
  { code: "ZWG",  name: "Zimbabwe Gold",         symbol: "ZiG",                      countries: [716] }
];

// All map countries excluded from the game are "distractors" that can be clicked.

// 🐻 Mode uses ONLY this classic study list. Every code here must also exist in
// CURRENCIES above; codes that no longer exist (e.g. MXV) are simply ignored.
const BEAR_CURRENCIES = [
  "ALL", "ARS", "AUD", "BGN", "BHD", "BRL", "CAD", "CHF", "CLP", "CNY",
  "COP", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF", "IDR", "ILS", "INR",
  "ISK", "JPY", "KRW", "MAD", "MXN", "MXV", "MYR", "NAD", "NGN", "NOK",
  "NZD", "PEN", "PHP", "RON", "RUB", "SAR", "SEK", "SGD", "THB", "TRY",
  "TWD", "USD", "VES", "VND", "XOF", "ZAR"
];