// U.S. states study pool (50 states + DC). code = FIPS id used by lib/us.js map.
const US_STATES = [
  { code: '01', name: 'Alabama', abbr: 'AL' },
  { code: '02', name: 'Alaska', abbr: 'AK' },
  { code: '04', name: 'Arizona', abbr: 'AZ' },
  { code: '08', name: 'Colorado', abbr: 'CO' },
  { code: '12', name: 'Florida', abbr: 'FL' },
  { code: '13', name: 'Georgia', abbr: 'GA' },
  { code: '18', name: 'Indiana', abbr: 'IN' },
  { code: '20', name: 'Kansas', abbr: 'KS' },
  { code: '23', name: 'Maine', abbr: 'ME' },
  { code: '25', name: 'Massachusetts', abbr: 'MA' },
  { code: '27', name: 'Minnesota', abbr: 'MN' },
  { code: '34', name: 'New Jersey', abbr: 'NJ' },
  { code: '37', name: 'North Carolina', abbr: 'NC' },
  { code: '38', name: 'North Dakota', abbr: 'ND' },
  { code: '40', name: 'Oklahoma', abbr: 'OK' },
  { code: '42', name: 'Pennsylvania', abbr: 'PA' },
  { code: '46', name: 'South Dakota', abbr: 'SD' },
  { code: '48', name: 'Texas', abbr: 'TX' },
  { code: '56', name: 'Wyoming', abbr: 'WY' },
  { code: '09', name: 'Connecticut', abbr: 'CT' },
  { code: '29', name: 'Missouri', abbr: 'MO' },
  { code: '54', name: 'West Virginia', abbr: 'WV' },
  { code: '17', name: 'Illinois', abbr: 'IL' },
  { code: '35', name: 'New Mexico', abbr: 'NM' },
  { code: '05', name: 'Arkansas', abbr: 'AR' },
  { code: '06', name: 'California', abbr: 'CA' },
  { code: '10', name: 'Delaware', abbr: 'DE' },
  { code: '11', name: 'District of Columbia', abbr: 'DC' },
  { code: '15', name: 'Hawaii', abbr: 'HI' },
  { code: '19', name: 'Iowa', abbr: 'IA' },
  { code: '21', name: 'Kentucky', abbr: 'KY' },
  { code: '24', name: 'Maryland', abbr: 'MD' },
  { code: '26', name: 'Michigan', abbr: 'MI' },
  { code: '28', name: 'Mississippi', abbr: 'MS' },
  { code: '30', name: 'Montana', abbr: 'MT' },
  { code: '33', name: 'New Hampshire', abbr: 'NH' },
  { code: '36', name: 'New York', abbr: 'NY' },
  { code: '39', name: 'Ohio', abbr: 'OH' },
  { code: '41', name: 'Oregon', abbr: 'OR' },
  { code: '47', name: 'Tennessee', abbr: 'TN' },
  { code: '49', name: 'Utah', abbr: 'UT' },
  { code: '51', name: 'Virginia', abbr: 'VA' },
  { code: '53', name: 'Washington', abbr: 'WA' },
  { code: '55', name: 'Wisconsin', abbr: 'WI' },
  { code: '31', name: 'Nebraska', abbr: 'NE' },
  { code: '45', name: 'South Carolina', abbr: 'SC' },
  { code: '16', name: 'Idaho', abbr: 'ID' },
  { code: '32', name: 'Nevada', abbr: 'NV' },
  { code: '50', name: 'Vermont', abbr: 'VT' },
  { code: '22', name: 'Louisiana', abbr: 'LA' },
  { code: '44', name: 'Rhode Island', abbr: 'RI' },
];
